    global Is
    global VbackSelect;
    global H
    global t
    global firstPoint
    global xs;
    global ys;
    global x1;
    global x2;
    global y1;
    global y2;
    global pl; 
    global nextPhase;
    global a0;
    global a;
    global dy;
    global dx;
    global xstart;
    global ystart;
    global bond
    global temp;
    global Rfind;
    global i;
    global j;
    global z;
    global sizea;
    global x;
    global y;
    global p;
    global A1;
    global A2;
    global B1;
    global B2;
    global contact1;
    global contact2;
    global index;
    global swtch;
    global firstContact;
    global fin;
    global vertical_contact;
    global sig1;
    global sig2;
    global ig0;
    global Gs;
    global dE;
    global E;
    global T1;
    global Ec;
    global h;
    global gs1;
    global change;
    global el;
    global el2;
    global gama1;
    global gama2;
    global GR;
    global GA;
    global Hold;
    global removingContinues;
    global rows;
    global columns;
    global Cntct1PlcSlct;
    global Cntct2PlcSlct;
    global TopG2;
    global TopG1;
    global value1;
    global value2;
    global value3;
    global Btop;
    global Bvalue;
    global ihere;
    global pw;
    global P1;
    global P2;
    global theta1;
    global theta2;
    global phi1;
    global phi2;
    global sigmax
    global sigmay
    global sigmaz
    global I
    global mag1
    global mag2
    global gca
    global count
    global Ttot
    